### PR TITLE
Allow optional config for Recode.Task.Format

### LINKED ISSUE #86: `Format` task is run, even if it's disabled in configuration
When running `mix recode` I would like to run only `Recode.Task.AliasOrder` task. 
However, `Recode.Task.Format` task seems to run always, even if it's explicitly marked as `active: false`. After running `mix recode` it shows both issues found by `Recode.Task.AliasOrder` and `Recode.Task.Format`, despite configuration.

My configuration:
```exs
[
  version: "0.7.2",
  # Can also be set/reset with `--autocorrect`/`--no-autocorrect`.
  autocorrect: false,
  # With "--dry" no changes will be written to the files.
  # Can also be set/reset with `--dry`/`--no-dry`.
  # If dry is true then verbose is also active.
  dry: true,
  # Enables or disables color in the output.
  color: true,
  # Can also be set/reset with `--verbose`/`--no-verbose`.
  verbose: false,
  # Can be overwritten by calling `mix recode "lib/**/*.ex"`.
  inputs: ["{mix,.formatter}.exs", "{apps,config,lib,test}/**/*.{ex,exs}"],
  formatters: [Recode.CLIFormatter],
  tasks: [
    # Tasks could be added by a tuple of the tasks module name and an options
    # keyword list. A task can be deactivated by `active: false`. The execution of
    # a deactivated task can be forced by calling `mix recode --task ModuleName`.
    {Recode.Task.AliasOrder, [active: true]},
    {Recode.Task.Format, [active: false]},
  ],
]
```
**Elixir version: 1.16.1**

I know that I can run `mix recode --task AliasOrder`, however I would like to use recode as a formatter plugin, so this is not possible this way.

**Context:** I don't want to use `Format` task, as in my case it changes some things that aren't changed by `mix format`, for example in some files (not in every case) it just adds empty line above comment or moves the comment 2 lines above. This is not an issue when just running `mix format` so I would like to not enable `Format` task when running `mix recode`. Maybe this is a separate bug, however in my opinion it should be allowed to disable `Format` task anyway.

### PR DESCRIPTION
**Pull request by NickNeck**
closes #86 

@szymonkozak you can now add an optional config for `Recode.Task.Format`:
```elixir
...
  tasks: [
    # the default, formats code with Sourceror 
    # {Recode.Task.Format, []}, 

    # formats code with Sourceror 
    # {Recode.Task.Format, config: [formatter: :sourceror]}, 
 
    # formats code with the Elixir formatter
    {Recode.Task.Format, config: [formatter: :elixir]}, 
 
    # deactivates the task
    # {Recode.Task.Format, active: false}, 
...
```

### CODE REVIEW

**Comment by szymonkozak** [comment]
Hi, thanks for the quick response! I have tested your solution.

Unfortunately after deactivating `Format` tasks it only doesn't report Format issues when running with `autocorrect: false` and `dry: true`. If `autocorrect` is set to `true` and `dry` to `false`, code is formatted despite of `Format tasks` being inactive.

Also, when using recode as a formatter, it stills adds some empty lines in some places, where they shouldn't. Even if the `Format` task is deactivated, or changed to `{Recode.Task.Format, config: [formatter: :elixir]},`

I have experimented with this code and I have discovered, that deactivating `Format` won't help in my issue because `Recode.Task.AliasOrder` formats the code anyway, even when `Format` task was disabled.  

Do you know any other ideas how to handle that? I would like to use `recode` only as a alias sorter working together with `mix format`, but right know it changes too many things that `mix format` doesn't change in my project.

**Comment by NickNeck** [comment]
Yes, when `recode` changes a file the file will also be formatted. The reason for this is that Recode manipulates the AST and we can only create the corresponding code if we format the AST. That is also the reason for the pre-formatter, so that all formatting changes are made in a first step.
The solution would be a change in `Sourceror`, I have opened a PR over there (https://github.com/doorgan/sourceror/pull/127). 

Do you have a code example thats will be not formatted correctly?  I could test it against my changes in `Sourceror`.

**Comment by szymonkozak** [comment]
Thank you. Sure, there are examples. All these are related to comments only.

**Example 1:**
```elixir
defmodule X do
  alias B
  alias A

  def y do
    1
    # test
  end
end
```
is changed to:
```elixir
defmodule X do
  alias A
  alias B

  def y do
    1

    # test
  end
end
```

So adds a new empty line before `# test` comment. 

**Example 2:**
```elixir
defmodule Y do
  alias B
  alias A
  
  def c do
    (fn y ->
      case z do
        p ->
          # test
           d

         u ->
           s
       end
     end).()
  end
end
```
is changed to:
```elixir
defmodule Y do
  alias A
  alias B

  def c do
    (fn y ->
       # test
       case z do
         p ->
           d

         u ->
           s
       end
     end).()
  end
end
```

So moves the comment a few lines up.

**Example 3 (the more complex one)**

```elixir
defmodule Z do
  alias B
  alias A
  
  def a do
    # test1

    # test2

    # line1
    # line2

    :ok
  end
  
  # test
  
  defp z do
    1
  end
end
```
is changed to:
```elixir
defmodule Z do
  alias A
  alias B

  def a do
    # test1
    # test2

    # line1
    # line2

    # test
    :ok
  end

  defp z do
    1
  end
end
```

As you can see the `# test` comment is moving from outside the function to the inside. 

**Example 4:**

```elixir
defmodule U do
  use Ecto.Schema
  
  alias B
  alias A

  schema "x" do
    field(:a, :string)
    field(:b, :string)
    # field(:c, :string)

    field(:d, :string)
  end
end
```
is changed to:
```elixir
defmodule U do
  use Ecto.Schema

  alias A
  alias B

  schema "x" do
    field(:a, :string)
    field(:b, :string)

    # field(:c, :string)

    field(:d, :string)
  end
end
```

There is a new empty line before commented field.

Without using recode, `mix format` doesn't change anything in this code.
I hope that's help you, if you need something more let me know.

**Comment by NickNeck** [comment]
Thank you for the examples. One of four is fixed. I will continue to try to fix this.

**Pull request merged**
